//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonVinci2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA
    {
        public string ASSET_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<decimal> OPERATING_HOURS { get; set; }
        public Nullable<decimal> INSTALLED_POWER { get; set; }
        public Nullable<decimal> WORK_AMOUNT { get; set; }
        public Nullable<decimal> ELECTRICITY_RATE { get; set; }
        public Nullable<decimal> ELECTRICITY_REVENUE { get; set; }
        public Nullable<decimal> CAPITAL_CHARGES { get; set; }
        public Nullable<decimal> C02_COSTS { get; set; }
        public Nullable<decimal> FUEL_COSTS { get; set; }
        public Nullable<decimal> ELECTRICITY_GENERATION_COSTS { get; set; }
        public Nullable<decimal> TOTAL_COSTS { get; set; }
        public Nullable<decimal> PROFITABILITIY { get; set; }
    }
}
